name: globoplay_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  flutter_dotenv: ^5.0.2
  cloud_firestore: ^4.9.3
  flutter_riverpod: ^2.3.0
  flutter_svg: ^2.0.14
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  freezed: ^2.4.4


flutter:
  uses-material-design: true
  assets:
    - assets/geral/
    - assets/icons/home/
    - assets/icons/star/