// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpBv2A6snPkrb1b7NrI-TRyj0ybyQPApk',
    appId: '1:940799567264:web:1b53c3a415107ac554b0c5',
    messagingSenderId: '940799567264',
    projectId: 'globoplay-flutter',
    authDomain: 'globoplay-flutter.firebaseapp.com',
    storageBucket: 'globoplay-flutter.firebasestorage.app',
    measurementId: 'G-C22C8P2Q9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgMcVAxAhoKuqxC2j3ft9IeD_1pHldAqE',
    appId: '1:940799567264:android:97703303bc369fe254b0c5',
    messagingSenderId: '940799567264',
    projectId: 'globoplay-flutter',
    storageBucket: 'globoplay-flutter.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpBv2A6snPkrb1b7NrI-TRyj0ybyQPApk',
    appId: '1:940799567264:web:0144dc0912706e4854b0c5',
    messagingSenderId: '940799567264',
    projectId: 'globoplay-flutter',
    authDomain: 'globoplay-flutter.firebaseapp.com',
    storageBucket: 'globoplay-flutter.firebasestorage.app',
    measurementId: 'G-CH4ZXJ7RWS',
  );
}
